<?php

namespace GenericDatabase\Engine;

use
  GenericDatabase\Traits\Errors,
  GenericDatabase\Traits\Caller,
  GenericDatabase\Traits\Cleaner,
  GenericDatabase\Traits\Singleton,
  GenericDatabase\Engine\FBird\Arguments,
  GenericDatabase\Engine\FBird\Options,
  GenericDatabase\Engine\FBird\Attributes,
  GenericDatabase\Engine\FBird\DSN,
  GenericDatabase\Engine\FBird\FBird,
  GenericDatabase\Engine\FBird\Dump,
  GenericDatabase\Engine\FBird\Transaction;

class FBirdEngine
{
  use Errors, Caller, Cleaner, Singleton;

  /**
   * This method is responsible for call the static instance to Arguments class with a Magic Method __call and __callStatic.
   * 
   * @param string $method
   * @param array $arguments
   * @return FBirdEngine
   */
  private static function call(string $method, array $arguments): FBirdEngine
  {
    return Arguments::call($method, $arguments);
  }

  /**
   * This method is responsible for prepare the connection options before connect.
   * 
   * @return FBirdEngine
   */
  private function preConnect(): FBirdEngine
  {
    Options::setOptions($this->getOptions());
    $options = [];
    $options = Options::getOptions();
    $this->setOptions($options);
    return $this;
  }

  /**
   * This method is responsible for update in date late binding the connection.
   * 
   * @return FBirdEngine
   */
  private function postConnect(): FBirdEngine
  {
    Options::define();
    Attributes::define();
    return $this;
  }

  /**
   * This method is responsible for creating a new instance of the FBirdEngine connection.
   * 
   * @param string $dsn
   * @return FBirdEngine 
   */
  private function realConnect(string $host = null, string $user, string $password = null, string $database, int $port): FBirdEngine
  {
    $dsn = vsprintf('%s/%s:%s', [$host, $port, $database]);
    $this->setConnection((string) !Options::getOptions(FBird::ATTR_PERSISTENT) ? fbird_connect($dsn, $user, $password) : fbird_pconnect($dsn, $user, $password));
    return $this;
  }

  /**
   * This method is used to establish a database connection and set the connection instance
   * 
   * @return FBirdEngine
   */
  public function connect(): FBirdEngine
  {
    try {
      $this
        ->preConnect()
        ->setInstance($this)
        ->setDsn($this->parseDsn())
        ->realConnect($this->getHost(), $this->getUser(), $this->getPassword(), $this->getDatabase(), $this->getPort())
        ->postConnect()
        ->setConnected(true);
      return $this;
    } catch (\Exception $error) {
      $this->setConnected(false);
      Errors::throw($error);
    }
  }

  /**
   * This method is responsible for parsing the DSN from DSN class.
   * 
   * @return string|\Exception
   */
  private function parseDsn(): string|\Exception
  {
    return DSN::parseDsn();
  }

  /**
   * This method is used to get the database connection instance
   * 
   * @return mixed
   */
  public function getConnection(): mixed
  {
    return $GLOBALS['connection'];
  }

  /**
   * This method is used to assign the database connection instance
   * 
   * @param mixed $connection
   * @return mixed
   */
  public function setConnection(mixed $connection): mixed
  {
    return $GLOBALS['connection'] = $connection;
  }

  /**
   * Import SQL dump from file - extremely fast.
   * 
   * @param string $file 
   * @param string $delimiter = ';'
   * @param array<callable(int, ?float): void> $onProgress = null
   * @return int
   */
  public function loadFromFile(string $file, string $delimiter = ';', ?callable $onProgress = null): int
  {
    return Dump::loadFromFile($file, $delimiter, $onProgress);
  }

  /**
   * This function creates a new transaction, in order to be able to commit or rollback changes made to the database.
   * 
   * @return bool
   */
  public function beginTransaction(): bool
  {
    return Transaction::beginTransaction();
  }

  /**
   * This function commits any changes made to the database during this transaction.
   * 
   * @return bool
   */
  public function commit(): bool
  {
    return Transaction::commit();
  }

  /**
   * This function rolls back any changes made to the database during this transaction and restores the data to its original state.
   * 
   * @return bool
   */
  public function rollback(): bool
  {
    return Transaction::rollback();
  }

  /**
   * This function returns the last ID generated by an auto-increment column, either the last one inserted during the current transaction, or by passing in the optional name parameter.
   * 
   * @return bool
   */
  public function inTransaction(): bool
  {
    return Transaction::inTransaction();
  }

  /**
   * This function returns the last ID generated by an auto-increment column, either the last one inserted during the current transaction, or by passing in the optional name parameter.
   * 
   * @param ?string $name = null
   * @return string|false
   */
  public function lastInsertId(?string $name = null): string | false
  {
    $autoKey = $this->query(vsprintf("SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE column_default LIKE 'nextval%%' AND table_name = '%s';", [$name]));
    $autoKeyRes = pg_fetch_assoc($autoKey);
    if (isset($autoKeyRes['column_name'])) {
      $maxIndex = $this->query(vsprintf("SELECT pg_catalog.setval(pg_get_serial_sequence('%s', '%s'), COALESCE(MAX(%s))) AS value FROM %s;", [$name, $autoKeyRes['column_name'], $autoKeyRes['column_name'], $name]));
      $maxIndexRes = pg_fetch_assoc($maxIndex);
      return $maxIndexRes['value'];
    } else {
      return 0;
    }
  }

  /**
   * This function quotes a string for use in an SQL statement and escapes special characters (such as quotes).
   * 
   * @param mixed $string
   * @param ?bool $quote = false
   * @return string|array|false
   */
  public function quote(mixed $string): string | array | false
  {
    $quoted = function ($string) {
      return str_replace("'", "''", $string);
    };

    if (is_int($string)) {
      return $string;
    } elseif (is_float($string)) {
      return "'" . $quoted(str_replace(',', '.', strval(floatval($string)))) . "'";
    } elseif (is_bool($string)) {
      return $string ? '1' : '0';
    } elseif (is_null($string)) {
      return 'NULL';
    } else {
      return "'" . $quoted($string) . "'";
    }
  }

  /**
   * This function prepares an SQL statement for execution and returns a statement object.
   * 
   * @param string $query
   * @param ?string $transaction = null
   * @return mixed
   */
  public function prepare(string $query, ?string $transaction = null): mixed
  {
    return (is_null($transaction) ? fbird_prepare($this->getInstance()->getConnection(), $query) : fbird_prepare($this->getInstance()->getConnection(), $transaction, $query));
  }

  /**
   * This function executes an SQL statement and returns the result set as a statement object.
   * 
   * @param string $query
   * @return object|false
   */
  public function query(string $query): mixed
  {
    return fbird_query($this->getInstance()->getConnection(), $query);
  }

  /**
   * This function runs an SQL statement and returns the number of affected rows.
   * 
   * @param mixed $query
   * @param mixed $params
   * @return mixed
   */
  public function exec(mixed $query, mixed $params): mixed
  {
    if (!is_array($params))
      return fbird_execute($query, $params);
    array_unshift($params, $query);
    $rc = call_user_func_array('fbird_execute', $params);
    return $rc;
  }

  /**
   * This function retrieves an attribute from the database.
   * 
   * @param int $attribute
   * @return mixed
   */
  public function getAttribute($name)
  {
    return FBird::getAttribute($name);
  }

  /**
   * This function returns an array containing error information about the last operation performed by the database.
   * 
   * @return string
   */
  public function setAttribute($name, $value)
  {
    return FBird::setAttribute($name, $value);
  }

  /**
   * This function returns an SQLSTATE code for the last operation executed by the database.
   * 
   * @return int
   */
  public function errorCode(): int
  {
    return fbird_errcode();
  }

  /**
   * This function returns an array containing error information about the last operation performed by the database.
   * 
   * @return string
   */
  public function errorInfo(): string
  {
    return fbird_errmsg();
  }
}
