<?php

namespace GenericDatabase\Engine;

use
  GenericDatabase\Traits\Errors,
  GenericDatabase\Traits\Caller,
  GenericDatabase\Traits\Cleaner,
  GenericDatabase\Traits\Singleton,
  GenericDatabase\Engine\PDO\Arguments,
  GenericDatabase\Engine\PDO\Options,
  GenericDatabase\Engine\PDO\Attributes,
  GenericDatabase\Engine\PDO\DSN,
  GenericDatabase\Engine\PDO\Dump,
  GenericDatabase\Engine\PDO\Transaction;

class PDOEngine
{
  use Errors, Caller, Cleaner, Singleton;

  /**
   * This method is responsible for call the static instance to Arguments class with a Magic Method __call and __callStatic.
   * 
   * @param string $method
   * @param array $arguments
   * @return PDOEngine
   */
  private static function call(string $method, array $arguments): PDOEngine
  {
    return Arguments::call($method, $arguments);
  }

  /**
   * This method is responsible for prepare the connection options before connect.
   * 
   * @return PDOEngine
   */
  private function preConnect(): PDOEngine
  {
    Options::setOptions($this->getOptions());
    $options = [];
    $options = Options::getOptions();
    $this->setOptions($options);
    return $this;
  }

  /**
   * This method is responsible for update in date late binding the connection.
   * 
   * @return PDOEngine
   */
  private function postConnect(): PDOEngine
  {
    Options::define();
    Attributes::define();
    return $this;
  }

  /**
   * This method is responsible for creating a new instance of the PDO connection.
   * 
   * @param string $dsn
   * @param ?string|null $user
   * @param ?string|null $password
   * @param ?array|null $options
   * @return PDOEngine 
   */
  private function realConnect(string $dsn, ?string $user = null, ?string $password = null, ?array $options = null): PDOEngine
  {
    $this->setConnection(new \PDO($dsn, $user, $password, $options));
    return $this;
  }

  /**
   * This method is used to establish a database connection and set the connection instance
   * 
   * @return PDOEngine
   */
  public function connect(): PDOEngine
  {
    try {
      $this
        ->setInstance($this)
        ->preConnect()
        ->realConnect($this->parseDsn(), $this->getUser(), $this->getPassword(), $this->getOptions())
        ->postConnect()
        ->setConnected(true);
      return $this;
    } catch (\PDOException | \Exception $error) {
      $this->setConnected(false);
      Errors::throw($error);
    }
  }

  /**
   * This method is responsible for parsing the DSN from DSN class.
   * 
   * @return string|\Exception
   */
  private function parseDsn(): string|\Exception
  {
    return DSN::parseDsn();
  }

  /**
   * This method is used to get the database connection instance
   * 
   * @return \PDO
   */
  public function getConnection(): \PDO
  {
    return $GLOBALS['connection'];
  }

  /**
   * This method is used to assign the database connection instance
   * 
   * @param \PDO $connection
   * @return \PDO
   */
  public function setConnection(\PDO $connection): \PDO
  {
    return $GLOBALS['connection'] = $connection;
  }

  /**
   * Import SQL dump from file - extremely fast.
   * 
   * @param string $file 
   * @param string $delimiter = ';'
   * @param array<callable(int, ?float): void> $onProgress = null
   * @return int
   */
  public function loadFromFile(string $file, string $delimiter = ';', ?callable $onProgress = null): int
  {
    return Dump::loadFromFile($file, $delimiter, $onProgress);
  }

  /**
   * This function creates a new transaction, in order to be able to commit or rollback changes made to the database.
   * 
   * @return bool
   */
  public function beginTransaction(): bool
  {
    return Transaction::beginTransaction();
  }

  /**
   * This function commits any changes made to the database during this transaction.
   * 
   * @return bool
   */
  public function commit(): bool
  {
    return Transaction::commit();
  }

  /**
   * This function rolls back any changes made to the database during this transaction and restores the data to its original state.
   * 
   * @return bool
   */
  public function rollback(): bool
  {
    return Transaction::rollback();
  }

  /**
   * This function returns the last ID generated by an auto-increment column, either the last one inserted during the current transaction, or by passing in the optional name parameter.
   * 
   * @return bool
   */
  public function inTransaction(): bool
  {
    return Transaction::inTransaction();
  }

  /**
   * This function returns the last ID generated by an auto-increment column, either the last one inserted during the current transaction, or by passing in the optional name parameter.
   * 
   * @param ?string $name = null
   * @return string|false
   */
  public function lastInsertId(?string $name = null): string | false
  {
    return $this->getInstance()->getConnection()->lastInsertId($name);
  }

  /**
   * This function quotes a string for use in an SQL statement and escapes special characters (such as quotes).
   * 
   * @param string $string
   * @param ?int $type = \PDO::PARAM_STR
   * @return string|false
   */
  public function quote(string $string, int $type = \PDO::PARAM_STR): string | false
  {
    return $this->getInstance()->getConnection()->quote($string, $type);
  }

  /**
   * This function prepares an SQL statement for execution and returns a statement object.
   * 
   * @param string $query
   * @param ?array $options
   * @return object|false
   */
  public function prepare(string $query, ?array $options = []): \PDOStatement | false
  {
    return $this->getInstance()->getConnection()->prepare($query, $options);
  }

  /**
   * This function executes an SQL statement and returns the result set as a statement object.
   * 
   * @param string $query
   * @param ?int $fetchMode = null
   * @return object|false
   */
  public function query(string $query, ?int $fetchMode = null): \PDOStatement | false
  {
    return $this->getInstance()->getConnection()->query($query, $fetchMode);
  }

  /**
   * This function runs an SQL statement and returns the number of affected rows.
   * 
   * @param string $query
   * @return int|false
   */
  public function exec(string $query): int | false
  {
    return $this->getInstance()->getConnection()->exec($query);
  }

  /**
   * This function retrieves an attribute from the database.
   * 
   * @param int $attribute
   * @return mixed
   */
  public function getAttribute(int $attribute): mixed
  {
    return $this->getInstance()->getConnection()->getAttribute($attribute);
  }

  /**
   * This function sets an attribute on the database.
   * 
   * @param int $attribute
   * @param string $value
   * @return \PDOStatement|false
   */
  public function setAttribute(int $attribute, string $value): \PDOStatement | false
  {
    return $this->getInstance()->getConnection()->setAttribute($attribute, $value);
  }

  /**
   * This function returns an SQLSTATE code for the last operation executed by the database.
   * 
   * @return ?string
   */
  public function errorCode(): ?string
  {
    return $this->getInstance()->getConnection()->errorCode();
  }

  /**
   * This function returns an array containing error information about the last operation performed by the database.
   * 
   * @return array
   */
  public function errorInfo(): array
  {
    return $this->getInstance()->getConnection()->errorInfo();
  }
}
